# **Experiment-8**

### Objective: 
Write a program to read text data from a file and perform Part of Speech Tagging, stop-word removal, stemming (using different stemmers), lemmatization and identify the difference between  stemming and lemmatization.

In [5]:
%pip install nltk pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nltk in c:\users\mainp\appdata\roaming\python\python313\site-packages (3.9.1)
Requirement already satisfied: pandas in c:\users\mainp\appdata\roaming\python\python313\site-packages (2.2.3)
Requirement already satisfied: click in c:\users\mainp\appdata\roaming\python\python313\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\mainp\appdata\roaming\python\python313\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\mainp\appdata\roaming\python\python313\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\mainp\appdata\roaming\python\python313\site-packages (from nltk) (4.67.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mainp\appdata\roaming\python\python313\site-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mainp\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mainp\appdata\roaming\python\python313\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mainp\appdata\roaming\python\python313\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\mainp\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: colorama in c:\users\mainp\appdata\roaming\python\python313\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [6]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, LancasterStemmer, SnowballStemmer
from nltk.stem import WordNetLemmatizer
import pandas as pd

# Download required NLTK data files
nltk.download("punkt", download_dir="C:/nltk_data")
nltk.download("stopwords", download_dir="C:/nltk_data")
nltk.download("averaged_perceptron_tagger", download_dir="C:/nltk_data")
nltk.download("wordnet", download_dir="C:/nltk_data")
nltk.download("omw-1.4", download_dir="C:/nltk_data")

[nltk_data] Downloading package punkt to C:/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to C:/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to C:/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to C:/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [7]:
def read_text_file(file_path):
    """Read text data from the specified file."""
    with open(file_path, 'r', encoding='utf-8') as file:
        text = file.read()
    return text

# Specify the file path
file_path = 'input.txt'

# Read the content of input.txt
text = read_text_file(file_path)
print("Content of input.txt:")
print(text)

Content of input.txt:
Microsoft announced a new product launch event in New York City on December 1st, 2024.
Elon Musk, the CEO of Tesla, hinted at a partnership with NASA for a Mars mission.
The GDP of India grew by 7% in the first quarter of 2023, according to a report by Reuters.
Amazon is planning to open a new data center in Dublin, Ireland next year.
Barack Obama gave a keynote speech at Stanford University last Thursday.
Bitcoin reached an all-time high of $68,000 in November 2021.
The Louvre Museum in Paris saw record-breaking attendance last summer.

In [8]:
# Tokenize the text
tokens = word_tokenize(text.lower())

# Load English stopwords
stop_words = set(stopwords.words("english"))

# Remove stopwords and filter non-alphabetic words
filtered_words = [word for word in tokens if word.isalpha() and word not in stop_words]

print("\nFiltered Words (After Stop-word Removal):")
print(filtered_words)

Filtered Words (After Stop-word Removal):
['microsoft', 'announced', 'new', 'product', 'launch', 'event', 'new', 'york', 'city', 'december', 'elon', 'musk', 'ceo', 'tesla', 'hinted', 'partnership', 'nasa', 'mars', 'mission', 'gdp', 'india', 'grew', 'first', 'quarter', 'according', 'report', 'reuters', 'amazon', 'planning', 'open', 'new', 'data', 'center', 'dublin', 'ireland', 'next', 'year', 'barack', 'obama', 'gave', 'keynote', 'speech', 'stanford', 'university', 'last', 'thursday', 'bitcoin', 'reached', 'high', 'november', 'louvre', 'museum', 'paris', 'saw', 'attendance', 'last', 'summer']

In [9]:
# Perform POS tagging
pos_tags = nltk.pos_tag(filtered_words)

# Display the POS tags
df_pos_tags = pd.DataFrame(pos_tags, columns=["Word", "POS Tag"])
df_pos_tags

           Word POS Tag
0     microsoft      RB
1     announced     VBD
2           new      JJ
3       product      NN
4        launch      JJ
5         event      NN
6           new      JJ
7          york      NN
8          city      NN
9      december     VBP
10         elon      NN
11         musk      NN
12          ceo      NN
13        tesla      NN
14       hinted     VBD
15  partnership      NN
16         nasa      JJ
17         mars     NNS
18      mission      NN
19          gdp      NN
20        india      NN
21         grew     VBD
22        first      JJ
23      quarter      NN
24    according     VBG
25       report      NN
26      reuters     NNS
27       amazon     VBP
28     planning     VBG
29         open      JJ
30          new      JJ
31         data     NNS
32       center      NN
33       dublin      NN
34      ireland      NN
35         next      JJ
36         year      NN
37       barack      NN
38        obama      NN
39         gave     VBD
40      keynote     VBN
41       speech      NN
42     stanford      NN
43   university      NN
44         last      JJ
45     thursday      JJ
46      bitcoin      NN
47      reached     VBD
48         high      JJ
49     november      NN
50       louvre      NN
51       museum      NN
52        paris      NN
53          saw     VBD
54   attendance      NN
55         last      JJ
56       summer      NN

In [10]:
# Initialize stemmers
porter_stemmer = PorterStemmer()
lancaster_stemmer = LancasterStemmer()
snowball_stemmer = SnowballStemmer("english")

# Apply stemming using different stemmers
porter_stems = [porter_stemmer.stem(word) for word in filtered_words]
lancaster_stems = [lancaster_stemmer.stem(word) for word in filtered_words]
snowball_stems = [snowball_stemmer.stem(word) for word in filtered_words]

# Create a DataFrame to compare results
df_stemming = pd.DataFrame({
    "Original Word": filtered_words,
    "Porter Stemmer": porter_stems,
    "Lancaster Stemmer": lancaster_stems,
    "Snowball Stemmer": snowball_stems
})
df_stemming

   Original Word Porter Stemmer Lancaster Stemmer Snowball Stemmer
0      microsoft      microsoft         microsoft        microsoft
1      announced        announc           annount          announc
2            new            new               new              new
3        product        product            produc          product
4         launch         launch            launch           launch
5          event          event                ev            event
6            new            new               new              new
7           york           york              york             york
8           city           citi              city             citi
9       december         decemb            decemb           decemb
10          elon           elon              elon             elon
11          musk           musk              musk             musk
12           ceo            ceo               ceo              ceo
13         tesla          tesla              tesl            tesla
14        hinted           hint              hint             hint
15   partnership    partnership             partn      partnership
16          nasa           nasa               nas             nasa
17          mars            mar               mar              mar
18       mission        mission              miss          mission
19           gdp            gdp               gdp              gdp
20         india          india               ind            india
21          grew           grew              grew             grew
22         first          first             first            first
23       quarter        quarter             quart          quarter
24     according         accord            accord           accord
25        report         report            report           report
26       reuters         reuter              reut           reuter
27        amazon         amazon            amazon           amazon
28      planning           plan              plan             plan
29          open           open                op             open
30           new            new               new              new
31          data           data               dat             data
32        center         center              cent           center
33        dublin         dublin            dublin           dublin
34       ireland        ireland           ireland          ireland
35          next           next              next             next
36          year           year              year             year
37        barack         barack            barack           barack
38         obama          obama              obam            obama
39          gave           gave               gav             gave
40       keynote         keynot            keynot           keynot
41        speech         speech            speech           speech
42      stanford       stanford          stanford         stanford
43    university        univers           univers          univers
44          last           last              last             last
45      thursday       thursday          thursday         thursday
46       bitcoin        bitcoin           bitcoin          bitcoin
47       reached          reach             reach            reach
48          high           high              high             high
49      november         novemb            novemb           novemb
50        louvre          louvr             louvr            louvr
51        museum         museum              muse           museum
52         paris           pari               par             pari
53           saw            saw               saw              saw
54    attendance         attend            attend           attend
55          last           last              last             last
56        summer         summer               sum           summer

In [11]:
# Initialize lemmatizer
lemmatizer = WordNetLemmatizer()

# Apply lemmatization
lemmatized_words = [lemmatizer.lemmatize(word) for word in filtered_words]

# Create a DataFrame to compare original words with lemmatized words
df_lemmatization = pd.DataFrame({
    "Original Word": filtered_words,
    "Lemmatized Word": lemmatized_words
})
df_lemmatization

   Original Word Lemmatized Word
0      microsoft       microsoft
1      announced       announced
2            new             new
3        product         product
4         launch          launch
5          event           event
6            new             new
7           york            york
8           city            city
9       december        december
10          elon            elon
11          musk            musk
12           ceo             ceo
13         tesla           tesla
14        hinted          hinted
15   partnership     partnership
16          nasa            nasa
17          mars             mar
18       mission         mission
19           gdp             gdp
20         india           india
21          grew            grew
22         first           first
23       quarter         quarter
24     according       according
25        report          report
26       reuters         reuters
27        amazon          amazon
28      planning        planning
29          open            open
30           new             new
31          data            data
32        center          center
33        dublin          dublin
34       ireland         ireland
35          next            next
36          year            year
37        barack          barack
38         obama           obama
39          gave            gave
40       keynote         keynote
41        speech          speech
42      stanford        stanford
43    university      university
44          last            last
45      thursday        thursday
46       bitcoin         bitcoin
47       reached         reached
48          high            high
49      november        november
50        louvre          louvre
51        museum          museum
52         paris           paris
53           saw             saw
54    attendance      attendance
55          last            last
56        summer          summer

In [12]:
# Display a comparison of stemming vs. lemmatization
df_comparison = pd.DataFrame({
    "Original Word": filtered_words,
    "Porter Stemmer": porter_stems,
    "Lemmatized Word": lemmatized_words
})

   Original Word Porter Stemmer Lemmatized Word
0      microsoft      microsoft       microsoft
1      announced        announc       announced
2            new            new             new
3        product        product         product
4         launch         launch          launch
5          event          event           event
6            new            new             new
7           york           york            york
8           city           citi            city
9       december         decemb        december
10          elon           elon            elon
11          musk           musk            musk
12           ceo            ceo             ceo
13         tesla          tesla           tesla
14        hinted           hint          hinted
15   partnership    partnership     partnership
16          nasa           nasa            nasa
17          mars            mar             mar
18       mission        mission         mission
19           gdp            gdp             gdp
20         india          india           india
21          grew           grew            grew
22         first          first           first
23       quarter        quarter         quarter
24     according         accord       according
25        report         report          report
26       reuters         reuter         reuters
27        amazon         amazon          amazon
28      planning           plan        planning
29          open           open            open
30           new            new             new
31          data           data            data
32        center         center          center
33        dublin         dublin          dublin
34       ireland        ireland         ireland
35          next           next            next
36          year           year            year
37        barack         barack          barack
38         obama          obama           obama
39          gave           gave            gave
40       keynote         keynot         keynote
41        speech         speech          speech
42      stanford       stanford        stanford
43    university        univers      university
44          last           last            last
45      thursday       thursday        thursday
46       bitcoin        bitcoin         bitcoin
47       reached          reach         reached
48          high           high            high
49      november         novemb        november
50        louvre          louvr          louvre
51        museum         museum          museum
52         paris           pari           paris
53           saw            saw             saw
54    attendance         attend      attendance
55          last           last            last
56        summer         summer          summer